### PR TITLE
Use gosu to change the user running nexus

### PR DESCRIPTION
**Pull request by feniix**
When using kubernetes with persistent storage volume the filesystem is owned by root, because we want to run nexus3 under the nexus user we need to chown the data volume to the nexus user, but we can only chown if we are root.

To allow this we start the container as root and then switch to nexus using `gosu` (https://github.com/tianon/gosu)

### CODE REVIEW

**Comment by feniix** [comment]
@jswank what do you guys think about this change?

**Comment by cavemandaveman** [comment]
Any movement on this? 
It's a great solution to this problem in the README:
> Mount a host directory as the volume. This is not portable, as it relies on the directory existing with correct permissions on the host.

[su-exec](https://github.com/ncopa/su-exec) is a little lighter, but would be more difficult to implement in CentOS, since it would require compiling from source instead of just downloading the binary like gosu.

**Comment by feniix** [comment]
fixed merge conflicts and upgraded gosu to its latest release

**Comment by garethahealy** [comment]
I don't think running the container as root, and then switching is a good idea. For instance, if you tried to use this setup in OpenShift (based on Kube), i don't think the container would be able to start,  as by default you are not allowed to run root based containers due to security config.

I would expect other Kube based platforms (i.e.: CoreOS) will also have similar restrictions.

My 2cents.

**Comment by Rotwang** [comment]
Other problem with "gosu" approach is that you kill "built-in" docker run facilities like: "-u" or "--group-add".

**Comment by bgdben** [comment]
I think its all kinda dumb.

**Comment by feniix** [comment]
@garethahealy I proposed this change to allow it to run on kubernetes with a persistent volume (backed by google cloud) and I tested it and it does work.

**Comment by garethahealy** [comment]
@feniix can't you just solve this via supplemental groups? OCP supports it (https://docs.openshift.org/latest/install_config/persistent_storage/pod_security_context.html#supplemental-groups) so presume k8s does as well.

**Comment by RiaanLab** [comment]
@feniix I had the exact same issue that you had with PVC and RBD on K8S. You can solve your issue by forcing the POD (I am doing it from a deployment but it will work in any form of the Pod stanza) by adding this section to the POD section in your config: 
...
...
      securityContext:
        fsGroup: 1234
...
...

(Note the fsGroup section)

example:
      containers:
        - name: nexus3
          image: sonatype/nexus3:3.3.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
            - containerPort: 5000
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
              readOnly: false
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus3-pvc-01
      securityContext:
        fsGroup: 1234

Good luck.

**Comment by mikaelbrannstrom-tradedoubler** [comment]
@feniix `securityContext` and `fsGroup` is the way to go, as @RiaanLab proposed. However, insert the `nexus` user id there, i.e. **200** (and not 1234 as in the example). Verified to work on Google cloud with k8s, statefulset and pvc with nexus3:3.6.0.

This pull request is not needed...

**Pull request closed without merging**
