### PR TITLE
Overhaul

### PR DESCRIPTION
**Pull request by cavemandaveman**
This is a huge change, but is much needed, as there are a ton of broken things with your current implementation, as noted by the commenters on [both](https://hub.docker.com/r/sonatype/docker-nexus3/) of your [repos](https://hub.docker.com/r/sonatype/nexus/).

-Follow Docker [best practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/)
-Change to Alpine, because it's more [lightweight](http://gliderlabs.viewdocs.io/docker-alpine/) than CentOS
-Change to OpenJDK to avoid [issues](http://blog.takipi.com/running-java-on-docker-youre-breaking-the-law/)
-Use an entrypoint script with [su-exec](https://github.com/ncopa/su-exec) to get past [permissions issues](https://github.com/tianon/gosu#why)
-Support SSL
-Implement actual working environment variables

### CODE REVIEW

**Comment by joedragons** [comment]
-1 as noted here https://github.com/sonatype/docker-nexus3/pull/27 Sonatype does not (currently) support OpenJDK and noted here https://github.com/sonatype/docker-nexus3/pull/16#issuecomment-233962575 does not (currently) support Alpine and is intentionally keeping on CentOS.
This is not meant to seem unappreciative of your work put in; I just don't expect your PR to get merged because of these reasons and wanted to give you a chance to change anything if you want it to.

**Comment by cavemandaveman** [comment]
Thank you for the info. I'm just trying to make the most efficient/minimal image I can.

Sonatype's documentation is severly lacking for Nexus 3. The closest to system requirements I've found is Nexus 2 [requirements](https://support.sonatype.com/hc/en-us/articles/213464208-Sonatype-Nexus-System-Requirements):

>Any Windows, Linux, or Macintosh operating system that can run a supported Sun/Oracle Java version will work. Other operating systems may work, but they are not tested by Sonatype.  See [here] (http://www.oracle.com/technetwork/java/javase/certconfig-2095354.html) for the list of Oracle certified operating systems.

The decision to use CentOS seems contradictory. While it can run the latest Oracle Java (just like Alpine can), CentOS is **not** an Oracle JDK Certified Operating System (just like Alpine is not). You may say that RHEL is on the list, but it is just as [different](http://community.redhat.com/centos-faq/#_centos) from CentOS as it is from Alpine. With RHEL, Oracle provides a maintained yum repo to install Java. With CentOS (and Alpine), you have to manually agree to Oracle's T&C's and download an rpm.

To reference the Docker Java [issues](http://blog.takipi.com/running-java-on-docker-youre-breaking-the-law/) again: 

> To put it in simple terms, if you’re downloading a Docker image that contains Oracle’s JDK, you’re not holding up your part in the agreement. The image might not contain the required files from Oracle, or whoever built it could have inserted a cookie that automatically approves Oracle’s Terms and Conditions for you. When you download Oracle’s JDK from the official website, you are required to manually click a box to approve the terms and conditions. By adding the cookie, the user is unaware of the terms or of his need to approve them.

So if Sonatype defines supported operating systems based on being Oracle certified, they are in a gray area using anything but Oracle Linux, RHEL, SLES, or Ubuntu (the only feasible one for a docker image being Ubuntu).

Looks like the options are an Ubuntu/OracleJDK image or an Alpine/OpenJDK image. In my opinion, Alpine is the way to go.

**Comment by bentmann** [comment]
From the peanut gallery: As the PR description details, this PR combines several changes. It is probably easier to consume those changes when presented as separate PRs.

**Comment by cavemandaveman** [comment]
I don't mind breaking it up, however, by changing the Dockerfile, I in turn need to add the entrypoint script and update the readme. That right there is like 90% of this PR. Also, there is no point in separating it out if they decide not to use it...

**Comment by bentmann** [comment]
> Also, there is no point in separating it out if they decide not to use it...

That's the key thing why I suggested to break it up: Some of the changes here appear to be controversial. By splitting things up, the stuff that is not controversial can more easily move forward. Anyway, just a thought.

**Comment by DarthHater** [comment]
As @bentmann suggested, please split this up. A bulk of our users are on CentOS or similar and as indicated, we support only the use of the Oracle JRE, not OpenJDK.

**Comment by DarthHater** [comment]
By the way @cavemandaveman I've updated the README.md for some of your changes as of today (naming mainly), so you can minimize some of your changes.

**Comment by cavemandaveman** [comment]
@DarthHater just to clarify, there are no plans to switch from CentOS with Oracle Java?

**Comment by DarthHater** [comment]
@cavemandaveman we've talked internally about it (and we use alpine for some internal test harnesses) but CentOS is what we support as an org, and OpenJDK has had issues running Nexus (primarily Pro) in the past. Unlikely to switch off of either.

**Comment by cavemandaveman** [comment]
Okay, in that case I'll go ahead and close this. I'll open smaller PRs based on some of my improvements within your constraints.

**Pull request closed without merging**
